services:
  # Moodle Backend Service
  - type: web
    name: lumina-moodle-backend
    env: docker
    region: oregon
    plan: free
    startTimeoutSeconds: 1800
    dockerfilePath: ./Dockerfile
    envVars:
      # Paste your connection strings into these in the Render Dashboard
      - key: DATABASE_URL
        value: postgresql://moodle_mnm7_user:wi0n2hFg025lR8V79TZGknzAjltcYcL1@dpg-d791f8lactks73ctvgag-a/moodle_mnm7
      - key: DB_USER
        value: moodle_mnm7_user
      - key: DB_PASS
        value: wi0n2hFg025lR8V79TZGknzAjltcYcL1
      - key: DB_NAME
        value: moodle_mnm7
      - key: DB_HOST
        value: dpg-d791f8lactks73ctvgag-a
      - key: MOODLE_DATA_DIR
        value: /var/moodledata
      - key: MOODLE_ADMIN_PASS
        value: Admin1234!
      - key: PORT
        value: 10000
