<?php
/**
 * Headless Moodle RBAC & Identity Matrix Seeder
 * 
 * Provisions:
 * - 10 Site Administrators
 * - 10 Instructors (Editing Teachers)
 * - 20 Diverse Users assigned to varying custom and core roles
 */

define('NO_MOODLE_COOKIES', true);
require_once(__DIR__ . '/config.php');
require_once($CFG->dirroot . '/user/lib.php');

global $DB, $CFG, $PAGE;

$PAGE->set_url(new moodle_url('/local_run_seed.php'));
$PAGE->set_context(context_system::instance());
$PAGE->set_pagelayout('admin'); 

function log_seed($msg) {
    echo "[RBAC SEEDER] " . $msg . PHP_EOL;
    flush();
}

// Ensure Roles Exist
$required_roles = [
    'manager' => 'Manager',
    'coursecreator' => 'Course Creator',
    'editingteacher' => 'Editing Teacher (Instructor)',
    'teacher' => 'Non-editing Teacher',
    'student' => 'Student',
    'auditor' => 'Auditor (Custom)',
    'reviewer' => 'QA Reviewer (Custom)',
    'support' => 'Student Support (Custom)'
];

$role_ids = [];
foreach ($required_roles as $shortname => $fullname) {
    if (!$DB->record_exists('role', ['shortname' => $shortname])) {
        $id = create_role($fullname, $shortname, "Autogenerated $fullname role");
        log_seed("Created Role: $shortname");
        $role_ids[$shortname] = $id;
    } else {
        $role_ids[$shortname] = $DB->get_field('role', 'id', ['shortname' => $shortname]);
    }
}

function ensure_user($username, $firstname, $lastname) {
    global $DB, $CFG;
    if ($DB->record_exists('user', ['username' => $username])) {
        return $DB->get_record('user', ['username' => $username]);
    }

    $user = new stdClass();
    $user->username          = $username;
    $user->password          = hash_internal_user_password('Password123!');
    $user->email             = "$username@lumina.example.com";
    $user->firstname         = $firstname;
    $user->lastname          = $lastname;
    $user->confirmed         = 1;
    $user->lang              = 'en';
    $user->timezone          = '99';
    $user->calendartype      = 'gregorian';
    $user->mailformat        = 1;
    $user->maildisplay       = 1;
    $user->maildigest        = 0;
    $user->autosubscribe     = 1;
    $user->trackforums       = 0;
    $user->mnethostid        = $CFG->mnet_localhost_id ?? 1;
    // Moodle 5.x fields
    $user->city              = '';
    $user->country           = '';
    $user->description       = '';
    $user->descriptionformat = FORMAT_HTML;
    $user->picture           = 0;
    
    $uid = user_create_user($user, false, false);
    return $DB->get_record('user', ['id' => $uid]);
}

// 1. Provision 10 Admins
log_seed("Provisioning 10 Administrators...");
$syscontext = context_system::instance();
for ($i = 1; $i <= 10; $i++) {
    $uname = "sysadmin_$i";
    $user = ensure_user($uname, "System", "Admin $i");
    
    // Assign site admin privileges
    $admins = explode(',', $CFG->siteadmins);
    if (!in_array($user->id, $admins)) {
        $admins[] = $user->id;
        set_config('siteadmins', implode(',', $admins));
    }
}
log_seed("System Administrators provisioned.");

// 2. Provision 10 Instructors (Editing Teachers at System or Course level)
log_seed("Provisioning 10 Instructors...");
for ($i = 1; $i <= 10; $i++) {
    $uname = "instructor_$i";
    $user = ensure_user($uname, "Expert", "Instructor $i");
    // Assign them as managers or coursecreators at system level for broad access, or just assign role assignments here.
    // We will give them Course Creator role globally so they can build.
    role_assign($role_ids['coursecreator'], $user->id, $syscontext->id);
}
log_seed("Instructors (Course Creators) provisioned.");

// 3. Provision 20 Diverse Users
log_seed("Provisioning 20 Diverse Role Users...");
$roles_pool = ['manager', 'editingteacher', 'teacher', 'student', 'auditor', 'reviewer', 'support'];
for ($i = 1; $i <= 20; $i++) {
    $role_key = $roles_pool[array_rand($roles_pool)];
    $uname = "user_{$role_key}_$i";
    $user = ensure_user($uname, "Diverse", "Persona $i");
    
    // Assign role at system context just to ensure they hold it somewhere globally
    role_assign($role_ids[$role_key], $user->id, $syscontext->id);
}
log_seed("Diverse personas provisioned.");

// 4. Create Web Service Tokens for all generated users
log_seed("Generating Web Service Tokens for APIs...");
$service = $DB->get_record('external_services', ['shortname' => 'moodle_mobile_app', 'enabled' => 1]);
if (!$service) {
    $service = $DB->get_record_select('external_services', 'enabled = 1', [], '*', IGNORE_MULTIPLE);
}
if ($service) {
    require_once($CFG->dirroot . '/lib/externallib.php');
    // Find all users we just created
    $sql = "SELECT id, username FROM {user} WHERE username LIKE 'sysadmin_%' OR username LIKE 'instructor_%' OR username LIKE 'user_%'";
    $users = $DB->get_records_sql($sql);
    foreach ($users as $u) {
        if (!$DB->record_exists('external_tokens', ['userid' => $u->id, 'externalserviceid' => $service->id])) {
            try {
                external_generate_token(EXTERNAL_TOKEN_PERMANENT, $service, $u->id, $syscontext);
            } catch (Exception $e) { }
        }
    }
}
log_seed("=== RBAC SEEDING COMPLETE ===");
